### ISSUE TITLE
Add pagination

### ISSUE THREAD

**Issue by mulholio** [eat-well/nutrimprove#10]
Not urgent until we have enough data, but we will want to add pagination at some point. 

There's some useful code here: https://zeit.co/guides/deploying-next-and-mysql-with-now#step-4:-creating-your-node.js-api

- [ ] Recommendations
- [ ] Foods

**Comment by WhiT3Kr0w** [comment]
Not relevant anymore. Scrollable tables being used. 
Will implement lazy loading when data gets too big.
