### ISSUE TITLE
Update URL

### ISSUE THREAD

**Issue by mulholio** [eat-well/nutrimprove#11]
In `lib/helpers.js` there is a function that gets the base url. Make this update more dynamically, ideally using some env variable from Now (something like 'alias' perhaps) or, failing that, with a hard-coded but more visible `.env` param

**Comment by mulholio** [comment]
Blocked by #3

**Comment by mulholio** [comment]
Marked as a bug as this could potentially cause issues down the line (although it is safe now)

**Comment by WhiT3Kr0w** [comment]
Obsolete
