### ISSUE TITLE
Add styled-components

### ISSUE THREAD

**Issue by mulholio** [eat-well/nutrimprove#4]
- [ ] Do the configuration work, including adding a `_document.js` (checkout out next-examples repo for an idea on how to configure this)
- [ ] Refactor existing styles to use `styled-components`

**Comment by WhiT3Kr0w** [comment]
I guess we can implement responsive capabilities with styled-components and media queries?

**Comment by mulholio** [comment]
Yep: https://www.styled-components.com/docs/advanced#media-templates

**Comment by WhiT3Kr0w** [comment]
Not relevant anymore. Using Material-UI withStyles (HOC).
